server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 10m
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  session:
    redis:
      namespace: spring:session
    store-type: redis
    data:
      redis:
        host: localhost
        port: 6379
        password: 1111
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: user01
    password: 111111
mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info


app:
  url:
    serverurl: http://172.16.20.115:81
    chatboturl: http://172.16.20.115
  dir:
    imgdir: file:C:/project/imgs/
    logdir: file:C:/project/logs/
    upload: C:/project/imgs/
  key:
    wkey1: ENC(FN+rJQL3jLpxqkY2BIyHVh+BlUbpR+hdM8v8FlGZsqyJP7yPa8fU2B+jSvkAdAdMilwy8XArHKTRQglexi3+9NXUuQPOWVqyJN0hoGLKzbH0XG8bT4BDtW4UJjd1/iaOe7/Q5KnYIXEklSWd+/q6Eg==)
    wkey2: ENC(twARCNZg2KV7P0HidCiRsEpQpjvJyJlPcSBvWfVJLwRDBsalTRLhkpHYMgAwuoxk)
    ncp-id: ENC(/omEIjlsceGJACAa6PbqMf3N5bXpHdBL)
    ncp-secret: ENC(xAzKCkqxJM4iUp6m6Sl0D4+yEOloKNmYqyxcfiE6GpAyyecmCYTveeHlYWlzRtnwrOm/c95IJ0s=)

    # /root/logs/